# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'vs2017-win2016'
  
variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test ShortGuid.Tests --configuration $(buildConfiguration) --logger trx
    dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --framework net46
    dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --framework netcoreapp2.1

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1

- script: dotnet pack --include-symbols /p:Configuration=release /p:PackageVersion=$(Build.BuildNumber) --verbosity Detailed

- task: NuGetCommand@2
  inputs:
    command: push
    versioningScheme: byEnvVar
    versionEnvVar: Build.BuildNumber